services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-local

    command:
      - mongod
      - --replSet
      - rs0
      - --bind_ip_all
      - --keyFile
      - /data/configdb/mongo-keyfile

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

    volumes:
      - mongodb_data:/data/db
      - ./mongo-keyfile:/data/configdb/mongo-keyfile

volumes:
  mongodb_data:
