backend = "glx";
vsync = true;

# fade animation
fading = true;
fade-delta = 5;

# blur
blur-method = "dual_kawase";
blur-strength = 4;
blur-background = true;

blur-background-exclude = [
  "class_g = 'Polybar'",
  "class_g = 'i3bar'"
];

# opacity
active-opacity = 1.0;
inactive-opacity = 0.85;

# rounded corners
corner-radius = 0;

# shadows
shadow = false;

# per-app opacity
opacity-rule = [
  "0.95:class_g = 'Alacritty'",
  "0.90:class_g = 'kitty'",
  "0.95:class_g = 'i3bar'"
];
